services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"