@authToken = {{tokenAPI.response.body.access_token}}

### Request the root path
GET {{API_URL}}/ HTTP/1.1
Accept: application/json


### Get All Posts
GET {{API_URL}}/posts HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}


### Get Posts with params
GET {{API_URL}}/posts?limit=3&skip=0&search=Foolish HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}



### Get a Post with id
GET {{API_URL}}/posts/9 HTTP/1.1
Accept: application/json


### Create a new Post
POST {{API_URL}}/posts HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Hello",
    "content": "World",
    "mal": "ware"
}


### Update a Post with id
PUT {{API_URL}}/posts/4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Ping",
    "content": "Pong"
}

### Delete a Post by id
DELETE {{API_URL}}/posts/2 HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}


### Create a User
POST {{API_URL}}/users HTTP/1.1
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}


### Get a User by id
GET {{API_URL}}/users/5 HTTP/1.1
Accept: application/json


### Login
# @name tokenAPI
POST {{API_URL}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=johndoe@example.com&password=12345678


### Like/dislike a Post
POST {{API_URL}}/votes HTTP/1.1
Authorization: Bearer {{authToken}}

{
    "post_id": 3
}