### Request the root path
GET {{API_URL}}/ HTTP/1.1
Accept: application/json


### Get all Posts
GET {{API_URL}}/posts HTTP/1.1
Accept: application/json


### Get a Post with id
GET {{API_URL}}/posts/5 HTTP/1.1
Accept: application/json


### Create a new Post
POST {{API_URL}}/posts HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "title": "Foo",
    "content": "Bar",
    "rating": 5
}


### Update a Post with id
PUT {{API_URL}}/posts/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "title": "Foo",
    "content": "Bar"
}

### Delete a Post by id
DELETE {{API_URL}}/posts/1 HTTP/1.1
Accept: application/json